In [1]:
import pandas as pd
import ast
import numpy as np
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

In [8]:
df = pd.read_csv('csv_results/result_2.csv')
df

seed                                               True  \
0     32  [0.8919009554410655, 0.3430863057232868, -0.83...   
1     34  [1.5659960799344281, -0.4803619457547359, -1.0...   
2     63  [1.5183510787843302, 2.3937143568473545, 2.542...   
3      3  [-0.8002904057913294, 1.0290506471787033, 0.44...   
4     98  [0.656405584432002, -1.207656509505517, 0.5993...   
..   ...                                                ...   
95    66  [-0.8265169580268706, -1.396541205475884, -0.9...   
96    26  [-2.137207159941018, -1.548716462312171, -0.40...   
97    11  [1.220552242568979, 0.6384145957159848, -0.789...   
98    74  [-0.5623526981463747, 0.37797869313613547, 0.4...   
99    56  [1.1277697917032894, -0.6167016375988958, -2.2...   

                                                 ARMA  \
0   [1.0708670033078274, 0.045295010634492594, 0.0...   
1   [0.5728656478990121, 0.8722564668815384, -1.14...   
2   [0.3674664350881277, 1.2091005911550354, 1.307...   
3   [-1.2886888740566862, 0.24135002736395833, 1.0...   
4   [0.89238032476624, -0.27793087143189765, -1.11...   
..                                                ...   
95  [0.057208584614709956, -0.8765536993483297, -0...   
96  [-0.48619488694345114, -1.6747748323959941, -0...   
97  [0.6584036723005278, 0.7042699585964356, -0.01...   
98  [-1.2582413580074092, 0.12240112919997226, 0.4...   
99  [1.4932332608483412, -0.1504634607184563, -0.7...   

                                             Informer  \
0   [0.9235166, -0.8422532, 0.26997042, -0.2850458...   
1   [0.66607714, 1.6161497, -0.61828256, -0.326716...   
2   [0.2307167, 2.2548645, 2.2283144, 2.5892067, -...   
3   [-0.26125476, -0.23857592, 1.5038482, -0.52734...   
4   [1.27839, -0.9615882, -2.1218083, 0.4638763, -...   
..                                                ...   
95  [0.6770726, -1.5640088, -1.1366386, -0.522153,...   
96  [-0.52151805, -1.8486162, -1.424893, -0.324820...   
97  [1.0719209, 1.5348401, -1.017097, -1.2511438, ...   
98  [-0.7307072, 0.41098374, 1.1880846, -0.5401081...   
99  [1.4856448, -1.674096, 0.12043425, -0.53591746...   

                                                  RNN  
0   [0.9083796739578247, 0.2892483174800873, 0.189...  
1   [0.5163570642471313, 0.7830658555030823, -1.17...  
2   [0.6111019253730774, 1.2310011386871338, 1.310...  
3   [-1.1923787593841553, 0.4831295907497406, 1.15...  
4   [0.7714531421661377, -0.23765885829925537, -1....  
..                                                ...  
95  [0.20048893988132477, -0.8639606833457947, -0....  
96  [-0.5499839782714844, -1.609950065612793, -0.3...  
97  [0.7054905891418457, 0.587988018989563, 0.1119...  
98  [-1.39805006980896, 0.11063544452190399, 0.619...  
99  [1.4205833673477173, -0.05256788805127144, -0....  

[100 rows x 5 columns]

In [9]:
arma_mse = mean_squared_error(np.array(df['True'].apply(ast.literal_eval).to_list()),np.array(df['ARMA'].apply(ast.literal_eval).to_list()),multioutput='raw_values')
informer_mse = mean_squared_error(np.array(df['True'].apply(ast.literal_eval).to_list()),np.array(df['Informer'].apply(ast.literal_eval).to_list()),multioutput='raw_values')
rnn_mse = mean_squared_error(np.array(df['True'].apply(ast.literal_eval).to_list()),np.array(df['RNN'].apply(ast.literal_eval).to_list()),multioutput='raw_values')


In [10]:
arma_mse

array([0.95996323, 0.96093931, 1.0060377 , 0.85977669, 0.83586359,
       0.86325898, 0.88492409, 0.79301731, 0.92128928, 1.22989937])

In [11]:
informer_mse

array([1.13593601, 1.69051894, 1.69641722, 1.55163967, 1.81079379,
       1.81304086, 2.00787966, 1.85230623, 2.43257684, 2.44292143])

In [12]:
rnn_mse

array([1.05525589, 1.00002805, 1.0382773 , 0.9198278 , 0.87116051,
       0.93560809, 0.87541737, 0.76993072, 0.91312381, 1.31914427])